
apiVersion: 1

datasources:
  - name: monitoring-prometheus-datasource
    type: prometheus
    access: proxy
    url: http://monitoring-prometheus:9090
    editable: true
  - name: monitoring-loki-datasource
    type: loki
    access: proxy
    url: http://monitoring-loki:3100
    editable: true
  - name: monitoring-loki-as-prometheus-datasource
    type: prometheus
    access: proxy
    url: http://monitoring-loki:3100/loki
    editable: true
  - name: monitoring-jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
  