version: "3.7"

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: monitoring-prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command: "--config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus"
    ports:
      - "9090:9090"
  promtail:
    image: grafana/promtail:latest
    container_name: monitoring-promtail
    volumes:
      - ./promtail/promtail-docker-config.yaml:/etc/promtail/docker-config.yaml
      - /tmp/logs:/var/log
    command: "--config.file=/etc/promtail/docker-config.yaml"
  loki:
    image: grafana/loki:latest
    container_name: monitoring-loki
    volumes:
      - ./loki/:/etc/loki/
    command: -config.file=/etc/loki/local-config.yml
    ports:
      - "3100:3100"
    restart: unless-stopped  
  grafana:
    image: grafana/grafana:latest
    container_name: monitoring-grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./grafana/example.json:/var/lib/grafana/dashboards/example.json
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - loki
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: monitoring-jaeger
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "16687:16687"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
  address-service:
    image: address-service:latest
    container_name: address-service
    environment:
      - OPENTRACING_JAEGER_HTTP-SENDER_URL=http://jaeger:14268/api/traces
      - LOGGER_DESTINATION_FILE=/var/log/address-service.log
    ports:
      - "8090:8090"
    volumes:
      - /tmp/logs:/var/log
  user-service:
    image: user-service:latest
    container_name: user-service
    environment:
      - OPENTRACING_JAEGER_HTTP-SENDER_URL=http://jaeger:14268/api/traces
      - LOGGER_DESTINATION_FILE=/var/log/user-service.log
      - CLIENT_ADDRESS_URL=http://address-service:8090
    ports:
      - "8080:8080"
    volumes:
      - /tmp/logs:/var/log
