spring:
  profiles:
    active: local
  application:
    name: user-service
  h2:
    console:
      enabled: true
      path: /user-console
      settings:
        trace: false
        web-allow-others: false
  datasource:
    url: jdbc:h2:mem:gadget-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: admin
    password: pwd123
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        use_sql_comments: true
        format_sql: true
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metric
          - prometheus
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
info:
  application:
    name: ${spring.application.name}
    description: User service application
    version: '@project.version@'

opentracing:
  jaeger:
    http-sender:
      url: http://localhost:14268/api/traces

logging:
  level:
    web: INFO
    root: INFO
client:
  address:
    url: http://localhost:8090

logger:
  destination:
    file: '../logs/${spring.application.name}.log'
