server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://monitoring-loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: user-service
    static_configs:
      - targets:
          - localhost
        labels:
          job: user-service
          __path__: /var/log/user-service.log
  - job_name: address-service
    static_configs:
      - targets:
          - localhost
        labels:
          job: address-service
          __path__: /var/log/address-service.log