server:
  port : 8090
spring:
  profiles:
    active: local
  application:
    name: address-service
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metric
          - prometheus
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
info:
  application:
    name: ${spring.application.name}
    description: Address service application
    version: '@project.version@'

opentracing:
  jaeger:
    http-sender:
      url: http://localhost:14268/api/traces
logger:
  destination:
    file: '../logs/${spring.application.name}.log'
